const Head = () => (
  <>
    <title> A M I G A </title>
    <meta content="width=device-width, initial-scale=1" name="viewport" />
    <meta
      name="Associação dos Militares Veteranos e Pensionistas de Militares de Guaratinguetá"
      content="Generated by create next app developer: Ariel Paixão"
    />
    <link rel="icon" href="/Logo.svg" />
  </>
);

export default Head;
