import bcrypt from 'bcryptjs';

module.exports = {
  users: [
    {
      name: 'Administrador',
      image: '',
      lastName: 'Amiga',
      email: 'admin@gmail.com',
      password: bcrypt.hashSync('Amiga2023!'),
      isAdmin: true,
    },
    {
      name: 'Usuário',
      image: '',
      lastName: 'Amiga',
      email: 'user@example.com',
      password: bcrypt.hashSync('Amiga2023!'),
      isAdmin: false,
    },
  ],

  registers: [
    {
      name: 'teste 0',
      slug: 'test-0',
      stageName: 'Nome de Guerra',
      postGraduation: 'SGT',
      CPF: '12312312312',
      rgCivil: '123456',
      rgMilitary: 'AB 123456',
      CEP: '12515125',
      number: '123',
      address: 'Guaicurus',
      neighborhood: 'Pedregulho',
      city: 'Guaratinguetá',
      uf: 'São Paulo',
      formation: 2022,
      email: '@gmail.com',
      tell: '12991199191',
      cell: '12010100100',
      status: 'inativo',
      lunchFryday: true,
      lunchSaturday: false,
      buyShirt: true,
      manyBuyShirt: 2,
      shirtSizes: {
        size1: 'XG',
        size2: 'GG',
        size3: '',
        size4: '',
        size5: '',
      },
      priceVeteran: 90,
      priceGuest: 160,
      totalPrice: 250,
      shirt: {
        size: 'GG',
      },
      manyGuests: 1,
      guest: {
        guest1: {
          name: 'Convidado',
          rg: '12345',
          kinship: 'Irmão',
          lunchFryday: true,
          lunchSaturday: true,
          guestBuyShirt: true,
        },
        guest2: {
          name: '',
          rg: '',
          kinship: '',
          lunchFryday: '',
          lunchSaturday: '',
          guestBuyShirt: '',
        },
        guest3: {
          name: '',
          rg: '',
          kinship: '',
          lunchFryday: '',
          lunchSaturday: '',
          guestBuyShirt: '',
        },
        guest4: {
          name: '',
          rg: '',
          kinship: '',
          lunchFryday: '',
          lunchSaturday: '',
          guestBuyShirt: '',
        },
        guest5: {
          name: '',
          rg: '',
          kinship: '',
          lunchFryday: '',
          lunchSaturday: '',
          guestBuyShirt: '',
        },
      },
    },
  ],
};
