module.exports = {
  registers: [
    {
      name: 'Ariel0',
      stageName: 'Paixão',
      postGraduation: 'SGT',
      CPF: '03131312391',
      rgCivil: '321654',
      rgMilitary: '2131454',
      CEP: '12515125',
      number: '321',
      address: 'logo ali',
      neighborhood: 'confia',
      city: 'guara',
      uf: 'SP',
      formation: 1972,
      email: 'exemplo@gmail.com',
      tellphone: '12991199191',
      cellphone: '12010100100',
      status: 'inativo',
      lunchFryday: true,
      lunchSaturday: false,
      buyShirt: false,
      shirt: {
        size: 'G',
      },
      manyGuests: 1,
      guest: {
        name: 'José',
        rg: 321654741,
        kinship: 'Pai',
        lunchFryday: true,
        lunchSaturday: false,
        guestBuyShirt: true,
        buyShirt: true,
        shirt: {
          size: true,
        },
      },
    },
  ],
};
